
    export   let systemObj = {
        investmentAmountLevelList:[
            {
                id:-1,
                name:"未定义"
                
            },
            {
                id:0,
                name:"一千以内"
            },
            {
                id:1,
                name:"一千到一万"
            },
            {
                id:2,
                name:"一万到五万"
            },
            {
                id:3,
                name:"五万到十万"
            },
            {
                id:4,
                name:"十万以上"
            }
        ],
        ratingList:[
            {
                id:1
            },
            {
                id:2
            },
            {
                id:3
            },
            {
                id:4
            },
            {
                id:5
            },
        ],
        releaseTimeRange:[
            {
                id:-1,
                name:"未定义"
                
            },
            {
                id:0,
                name:"一周内"
            },
            {
                id:1,
                name:"一月内"
            },
            {
                id:2,
                name:"三个月内"
            },
            {
                id:3,
                name:"六月内"
            },
            {
                id:4,
                name:"一年内"
            }
        ],
        sceneCategory:[
            {
                id:-1,
                name:"未定义"
                
            },
            {
                id:0,
                name:"线上"
            },
            {
                id:1,
                name:"线下"
            },
        ],
        workTimeCategory:[
            {
                id:-1,
                name:"未定义"
                
            },
            {
                id:0,
                name:"全职"
            },
            {
                id:1,
                name:"兼职"
            },
        ],
        smsType:[
            {
                id:1,
                name:"登录"
            },
        ],
        fileType:[
            {
                id:1,
                name:"头像"
            },
        ],
        categoryId:[
            {
                id:'-1',
                name:"未定义"
                
            },
            {
                id:"newest",
                name:"最新"
            },
            {
                id:"hot",
                name:"热门"
            },
        ]
    }